### ISSUE TITLE
Improve performance when opening the application from tray

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#10]
When opening the tool from the tray icon, currently the application re-initializes itself completely.
This causes a major performance issue on an operation that is intended to be quick and seamless.

We need to prevent this and make sure that the application keeps its state even though it is minimized to the tray.

**Comment by krzysztof-lorenc** [comment]
I'm not sure if that is actually a problem. For example, new versions of Skype works also exactly that way.
The benefit of this is lower memory consumption, assuming that we free the memory correctly.

**Comment by steffen-wilke** [comment]
It is a problem. Depending on the configuration, it takes up **multiple seconds** for the application to even show up. For a tool that is intended to provide a quick overview, this is a major UX issue.

**Comment by dominikgolda** [comment]
Fixed in ecbe58a0

**Comment by dominikgolda** [comment]
I tried using VirtualizingStackPanel.IsVirtualizing="True" in ConnectorsTreeView.mainTreeView. It improves show performance, but it has some side effects.
1. If you have partially visible expanded group - like on screenshot below - the app will eat lot of CPU. I doesn't happen in simple app, but it my be difficult to find what we are doing wrong.
![2020-01-17_11h36_54](https://user-images.githubusercontent.com/7096402/72605755-aac39280-391d-11ea-801b-f4c73ded193f.png)
2. Improvement is strongly dependent on how many projects are visible on screen. If all are visible at once then there is no difference.
3. Sometimes when opening/closing/opening window fast exception is thrown. See [here](https://social.msdn.microsoft.com/Forums/en-US/8d7cfe9c-d9ad-4250-b760-e494e9f61bc2/height-must-be-nonnegative?forum=wpf). I haven't found 100% working solution for this.

**Comment by dominikgolda** [comment]
We no longer close the window when it is minimized to tray.
