### ISSUE TITLE
Memory consumption raise up with  each opening from tray icon

### ISSUE THREAD

**Issue by Bjo-Frei** [Soloplan/whatson#12]
WIth every opening the windows from task bar icon, the memory will be raised up. By closing the window (not application) not the new memory conusmption will be released.

I start with round 100 MB. After 5 cycling of minimize and opening the windows the memory is by round 300 MB,
After 10 cycle the memory is by 450 MB.

**Comment by dominikgolda** [comment]
I have fixed at least the part of the problem. Binding for ConnectorsTreeView is created in code and this requires it to be clear in code - this was responsible for most of the problem. Additionally I unsubscribed some events and now the ConnectorsTreeView/MainWindow are colected by GC. There are still some problems, but they are not so severe.

**Comment by dominikgolda** [comment]
Should be fixed. The memory usage should decrease a bit, because we now reuse the tooltip for build as static resources.
