### ISSUE TITLE
Add search/filter to the project selection wizard 

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#14]
The project selection right now shows all the build jobs of a particular server. Depending on the amout of jobs, it's very tedious to find the job that one is actually looking for.

The project selection should provide the user with a search bar to support filtering for relevant build jobs.

**Comment by krzysztof-lorenc** [comment]
![rLMK0kBAoX](https://user-images.githubusercontent.com/29510722/74030609-c1ef2080-49af-11ea-8851-412b3cb09182.png)
1) Searching filters the items in tree view
2) Checked items are always visible, regardless the filtering
3) The subgroups are checked automatically if all the sub items are checked (this considers the filtering)
