### ISSUE TITLE
Show job description in the project selection wizard

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#15]
The project selection wizard currently only displays the name of build jobs. If the build job has a description it should be displayed somewhere in the tree.
Without further context, it might be unclear what a certain build job does and whether it's the particular on of interest.

This could be realized as a `tooltip` or maybe some textbox at the bottom of the wizard that displays details about a job.

It could also be helpful to have a link to the job somewhere in the wizard to even provide more information about the job upon request.

**Comment by skowront** [comment]
Done.  https://github.com/Soloplan/whatson/pull/44 already checked and merged by @krzysztof-lorenc

**Comment by skowront** [comment]
fixed in #44
