### ISSUE TITLE
Add indicator(s) to groups

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#16]
If a group is currently collapsed, the tool doesn't provide any information about the contained jobs.
To get a quick overview, the groups should display additional information about their jobs **when they're collapsed**.

Example:
![image](https://user-images.githubusercontent.com/7015370/72243893-52268980-35ed-11ea-98f1-155ef480bf5d.png)

Only **the ones that apply** should be displayed.

**Comment by dominikgolda** [comment]
After some experimenting I don't think it is good idea. It looks good when groups are collapsed, but after they are expanded the information for groups mix with information for particular build jobs. The configuration with indicators in the middle doesn't have this problem, but it breaks the current column layout and makes using long group captions problematic.
![indicatorsAtTheEnd](https://user-images.githubusercontent.com/7096402/72630496-c1381100-3952-11ea-98ec-38093ba5acde.png)
![indicatiorsInTheMiddle](https://user-images.githubusercontent.com/7096402/72630503-c4cb9800-3952-11ea-8eb6-7312699af027.png)
![indicatorsAtTheBegining](https://user-images.githubusercontent.com/7096402/72630506-c6955b80-3952-11ea-9e9b-eaf102a4d092.png)

I have alternative version, we can have colored boxes with number of build jobs in given state inside. This will take less space, as the number/symbol are combined. Also the boxes look less like build job status indicators indicators and are not that much confused with one another.
![2020-01-17_18h09_29](https://user-images.githubusercontent.com/7096402/72631423-82a35600-3954-11ea-950a-8b1a7c251c66.png)

**Comment by dominikgolda** [comment]
- Count of build jobs in group is only shown when when group is collapsed.
- The indicator of number of builds in group are right aligned and not shown in columns.
