### ISSUE TITLE
Assign groups to new build jobs

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#19]
If new jobs are added with the project selection wizard, it is possible to select parent objects (in Jenkins: folders) in the wizard. This will select all of the child jobs but when currently adding them to the configuration, the information about the parent is lost and all jobs are being added to an empty group.

The configuration wizard should take over the first level of parents as groups in the application.
If the hierarchy is deeper, the wizard could indicate this by combining the names of the parents e.g. with slashes:

- [x]  Tools
   - [x] Custom
      - [x] Awesome Tool
      - [x] Another Tool

**Result:**

Tools/Custom
  - Awesome Tool
  - Another Tool

It could be an option in the wizard to provide this information within the job names (as currently supported by the master branch of the tool).

**Alternative Result:**

Custom
  - Tools/Custom/Awesome Tool
  - Tools/Custom/Another Tool

The most important thing is that a parent group gets actually created/used instead of just creating am empty group. If a parent group already exists, the jobs should be added to it instead.

**Comment by krzysztof-lorenc** [comment]
This is done.
In wizard, there is a new drop down which allows to select how the groups are managed.
There are 3 options:
1) Assign groups for added projects
2) Add project path to project name
3) Do not assign any groups

Also, the last selected option is saved, so when you use wizard another time, previously selected setting is restored.
