### ISSUE TITLE
Disappearing project configuration

### ISSUE THREAD

**Issue by krzysztof-lorenc** [Soloplan/whatson#29]
Problem with disappearing project configuration window when "Always on top" is active.
If you open the configuration for a project, then click the add button to add new configuration, window to select the type and name is shown.
Now, when that is open and you click outside the entire app window, that project configuration window is then hidden.

Internal bug id: 60964
Internal bug note id: 376069

**Comment by skowront** [comment]
Problem solved. Took few hours but finally it works correctly. All there was required:
&lt;materialDesign:DialogHost.Style> <Style BasedOn="{StaticResource MaterialDesignEmbeddedDialogHost}" TargetType="{x:Type materialDesign:DialogHost}"> </Style> </materialDesign:DialogHost.Style&gt;
there is a pull request fixing the problem:
[PullRequest](https://github.com/Soloplan/whatson/pull/53)
