### ISSUE TITLE
Adding CC.NET build job doesn't work properly

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#33]
I've tried adding a new CC.NET build job to WhatsON but failed multiple times before actually getting the "correct" URL format for the tool to work.

The wizard itself supports all of the formats to extract project information from the CC.NET server.
However, once the jobs are added from the wizard and saved to the `configuration.json`, the saved address is not brought into a usable format for the WhatsON plugin to extract server information.

The wizard supports the following formats:

1. `http://buildserver.com/ccnet/`
2. `http://buildserver.com/ccnet/ViewFarmReport.aspx`
3. `http://buildserver.com/ccnet/server/MyServer/ViewServerReport.aspx`
4. `http://buildserver.com/ccnet/server/MyServer/project/MyProject/ViewProjectReport.aspx`

**4.** is the only URL that produces a usable project from the wizard. All other URLs seem to work for project discovery but don't work for configured WhatsON projects anymore.
I would argue, that this URL is not the right one to use for project discovery because it's project specific, but right now, its the only URL that produces a usable configuration.

A few thoughts on this: We should either force restrictions on the supported URLs for CC.NET or a better solution would be to detect the format, normalize it to something that works and save the projects to the `configuration.json` in a sanitized format. Maybe the plugin also needs to be extended to handle the URLs more gracefully.

**Comment by skowront** [comment]
Fixed in https://github.com/Soloplan/whatson/pull/47 with issue #40.
