### ISSUE TITLE
Group context menu should be available for "default" group 

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#35]
Groups in WhatsON provide a context menu to "rename, delete and export".
This context menu is currently not available for the "default" group (i.e. the group without a name/caption).

When adding a new project without grouping, the project will be displayed under the default group. Instead of directly "renaming" this group, the user would have to first "Add new group" and then move the project(s) to the newly created group, which is inconvenient.

**Comment by dominikgolda** [comment]
Fixed together with #38
