### ISSUE TITLE
Projects that can't connect show last activity as 2020 years ago.

### ISSUE THREAD

**Issue by bytefluxio** [Soloplan/whatson#4]
We have a build project that has been discontinued.
The last activity/update time shows 2020 years ago instead of mentioning that the connection couldn't be established.

I imagine, that projects that aren't discontinued, but just can't be connected to right now, might have the same issue.

![2019-11-13_14-55-07](https://user-images.githubusercontent.com/29196542/68770231-0f185c00-0626-11ea-96d7-59d7f7969c34.png)

**Comment by steffen-wilke** [comment]
Possibly duplicate of #7

**Comment by steffen-wilke** [comment]
Closing this as duplicate, in favor for #7
