### ISSUE TITLE
"Open website" uses wrong URL for CruiseControl projects

### ISSUE THREAD

**Issue by BrightLight** [Soloplan/whatson#40]
For CruiseControl projects, the wrong URL is used to open the project dashboard (via Doubleclick on the project or "Open Website" from the context menu).

I get
`http://buildserver.com/ccnet/project/.Net%20Branch%20xyz/ViewProjectReport.aspx`

But correct would be
`http://cisnet.soloplan.de/ccnet/server/.Net/project/.Net%20Branch%20xyz/ViewProjectReport.aspx`

(This might be related to #33)

**Comment by skowront** [comment]
This and #33 should be working properly right now.
