### ISSUE TITLE
Opened window is not shown in task bar

### ISSUE THREAD

**Issue by sven-n** [Soloplan/whatson#5]
Version: v0.9.1-beta
OS: Windows 8.1 Enterprise

When WhatsON is opened, it doesn't appear in the task bar. When other windows are in front and I want to focus a previously opened WhatsON, I either have to use Alt+Tab or click on the tray icon.

Now the issue: Sometimes I don't remember that I opened it before, and double-click on the tray icon. Unfortunately, this closes the window and I have to do another double-click to open it again - with additional loading time and lost focus.

I know, this behaves similar to CCTray or other internal Tools we use, but there it re-opens instantly. If you look at other programs (like MS Outlook or Skype) this is not a standard behavior. I would assume that every opened main window of a program appears in the task bar.

**Comment by steffen-wilke** [comment]
Thanks for reporting this. Actually there's an option in the configuration that allows you to display the tool in the taskbar:

![image](https://user-images.githubusercontent.com/7015370/71071009-1cbc8680-217c-11ea-9609-822e925ef111.png)

Also, I totally agree that the time it currently takes for WhatsON to be displayed again from the tray is way too long. I'll keep this issue open to track this.

**Comment by sven-n** [comment]
Thanks for the hint.
To reduce the loading time and to keep the focus when re-opening, you could leave the dialog instance alive and just hide it instead of actually closing it.

**Comment by sven-n** [comment]
My previous suggestion would also solve #10, #11 and #12.
I think the higher memory consumption is negligible.

**Comment by dominikgolda** [comment]
@sven-n sugestion was implemented to fix performance issues (#10). The behavior of minimize button wasn't changed.

**Comment by sven-n** [comment]
Great, thank you 👍🏻
