### ISSUE TITLE
"Discovery of suitable plugin or server query timed out"

### ISSUE THREAD

**Issue by BrightLight** [Soloplan/whatson#6]
When I use the Wizard (Configuration -> Projects -> Use wizard"), select our Jenkins build server and click on "next" I get a connection error: "Discovery of suitable plugin or server query timed out"
![2019-12-18 DiscoveryOfSuitablePlugInTimeout](https://user-images.githubusercontent.com/1859278/71063138-6e5d1500-216c-11ea-846f-e73977b880df.png)

When I use the "+" at the top -> "Add project(s)", apparently the same wizard opens, but this time when I click on "Next" the connection works and it shows me available build jobs.
I'm on version 0.9.1.0.

**Comment by krzysztof-lorenc** [comment]
This will be fixed in next release.
