### ISSUE TITLE
Automatic detection of plugin type in wizard

### ISSUE THREAD

**Issue by krzysztof-lorenc** [Soloplan/whatson#65]
The wizard should be able to automatically detect the plugin type from URL.
Possible approach which was available some time ago but was removed:
- the feature should try to get results from each available plugin in separate threads. The plugin which return valid results is the one which should be used.
- the list of possible servers shown as hint in drop down should be a list combined from all possible server
- in case user selects already existing server address we can detect the plugin directly by that address - in such a case checking the results is not necessary.
- in UI, the type selection control on first wizard page should be removed(or we can leave it but there should be an "auto" mode used by default).

**Comment by skowront** [comment]
Done in #68
