### ISSUE TITLE
Currently master binaries cause exceptions and result in crash

### ISSUE THREAD

**Issue by steffen-wilke** [Soloplan/whatson#69]
To reproduce this, I can send you my WhatsON configuration via PM.

**Error log:**

[whatsON.log](https://github.com/Soloplan/whatson/files/5095278/whatsON.log)

**Comment by skowront** [comment]
Connected to post build events that copy the jenkins and cc libraries into /plugins.

Plugins folder logic removed from code in https://github.com/Soloplan/whatson/pull/70/commits/db2bb174f4b7d2ed48c6831de16e700fba6e79b0

**Comment by skowront** [comment]
Fixed with #70
