### ISSUE TITLE
Obsolete jobs are not shown as such (aka "missing visual feedback")

### ISSUE THREAD

**Issue by BrightLight** [Soloplan/whatson#7]
I have a couple of projects in WhatsOn that (I guess) no longer exist on our build servers. However, there is currently _zero_ feedback to go on, _why_ they don't show any meaningful information (no build label, no last build time, etc.).
![2019-12-18_ObsoleteProjects](https://user-images.githubusercontent.com/1859278/71063707-9600ad00-216d-11ea-962d-4fa9be3ff3a8.png)

In my opinion a UI should give visual feedback that something is wrong. For instance it should somehow indicate that it can't retrieve information of a project. Ideally it also provides means to get additional information on the details (is the server not available? is the server available, but does not know such a project? other causes?).

CCTray, in comparison, shows a grey icon next to projects for which it can't retrieve information.

**Comment by steffen-wilke** [comment]
Adding a project before the first build also produces the same visual result as mentioned above, even though nothing is "wrong" with the build job.

At least the following cases should be distinguishable:

* Server not available
* Project not available
* No Builds yet (aka. no Status)

WhatsON already has an `UNKNOWN` state. We should add an icon for it and the logic should be extended to provide additional information in the ToolTip of the icon.
