### ISSUE TITLE
Wasted space / missing compact overview in project selection

### ISSUE THREAD

**Issue by BrightLight** [Soloplan/whatson#8]
I'm not happy with the "Project selection" wizard. 
a) if you have several servers you have to open this wizard for each one of them separately
b) in my opinion it should show more data in less space. The UI might be okay for touchscreen use, but I'm on a desktop with a keyboard and mouse and I want data, not empty space.
CCTray showed all servers it knew of on the left side and available projects of the selected server in a concise list on the right side.
![2019-12-18_CCTray_AddProject](https://user-images.githubusercontent.com/1859278/71064601-bdf11000-216f-11ea-9ae3-219f87f1c5d5.png)

I'm aware that build jobs in Jenkins might be organized in folders, leading to a hierarchical structure. But still..., WhatsON wastes a lot of space.
![2019-12-18_WhatsOn_AddProject](https://user-images.githubusercontent.com/1859278/71064599-bdf11000-216f-11ea-9e79-bf6c0e3a6bcc.png)

Suggestions: 
  * make this view more condense
  * support multiple servers at once (servers could be the top nodes)
  * provide an option to hide already added build jobs (usually I'm using the "add project" wizard only for jobs that I have not yet added)

**Comment by dominikgolda** [comment]
I have set the padding to 0 - ecbe58a0
